// (c) Copyright 2010 Odiago, Inc.

package com.odiago.rtengine.exec;

import com.odiago.rtengine.thrift.TFlowId;
import com.odiago.rtengine.thrift.TQuerySubmitResponse;

/**
 * After the user submits a query to the planner, this response
 * is provided with information for the client to make use of.
 */
public class QuerySubmitResponse {
  private final String mMsg;
  private final FlowId mFlowId;

  public QuerySubmitResponse(String msg, FlowId flowId) {
    mMsg = msg;
    mFlowId = flowId;
  }

  /**
   * @return any message which the user should see regarding the query.
   */
  public String getMessage() {
    return mMsg;
  }

  /**
   * @return The FlowId, if any, which was generated by a successfully-submitted
   * flow based on this query.
   */
  public FlowId getFlowId() {
    return mFlowId;
  }

  public TQuerySubmitResponse toThrift() {
    TFlowId tId = mFlowId == null ? null : mFlowId.toThrift();
    TQuerySubmitResponse qsr = new TQuerySubmitResponse();
    qsr.setMsg(mMsg);
    qsr.setFlowId(tId);
    return qsr;
  }

  public static QuerySubmitResponse fromThrift(TQuerySubmitResponse other) {
    String msg = other.getMsg();
    TFlowId tId = other.getFlowId();
    FlowId id = tId == null ? null : FlowId.fromThrift(tId);
    return new QuerySubmitResponse(msg, id);
  }
}
